### PR TITLE
Update wmr.c

### PR DESCRIPTION
**Pull request by l33tlinuxh4x0r**
Fixes vertical sensor calibration for looking up and down.

### CODE REVIEW

**Comment by thaytan** [comment]
Slightly cleaner just to remove the negative sign from the -0.125f constant, but that's just a nitpick. An actual problem is that the accelerometer reading also needs to negation on the X axis removed, otherwise the fusion will always try and apply gravity correction in the wrong direction.

**Comment by l33tlinuxh4x0r** [comment]
agreed... that is more elegant.

**Comment by thaytan** [comment]
I made the simpler change, plus accelerometer change directly in my branch. Let me know if it does/doesn't work for you now

**Comment by l33tlinuxh4x0r** [comment]
I am having the same issues that I was having before the fixes. Something either on my end or with the code has messed things up.

**Comment by l33tlinuxh4x0r** [comment]
It is working as expected. Thanks for the fixes... now if only we can get the controllers to work.

**Comment by l33tlinuxh4x0r** [comment]
I did notice that when I calibrated the room the headset is always in/on the floor no matter how I move. Other head tracking appears to be working though.

**Pull request closed without merging**
